### PR TITLE
added new method decode_data_from_str to LiqPay class

### PR DESCRIPTION
**Pull request by barbossa**
What is done:
- added new method LiqPay.decode_data_from_str()
- added doctsrting to decode_data_from_str

### CODE REVIEW

**Review by wowkin2 — APPROVED** [review]

**Comment by barbossa** [comment]
@wowkin2 Thanks for approving. Can you merge this pull request to master?

**Comment by wowkin2** [comment]
@barbosa, unfortunately no, only comment

**Comment by barbossa** [comment]
@wowkin2 thanks for quick answer.
can you ask someone who can? :)

**Comment by viplifes** [comment]
Thanks

**Pull request merged**
